---

detectors:
  IrresponsibleModule:
    enabled: false

  ControlParameter:
    exclude:
      - HealthcheckEndpoint::Configuration#raise_unless
      - HealthcheckEndpoint::Configuration#validator_argument_type

  LongParameterList:
    exclude:
      - HealthcheckEndpoint::Configuration#raise_unless

  ManualDispatch:
    exclude:
      - HealthcheckEndpoint::Configuration#validator_services_callable

  TooManyConstants:
    exclude:
      - HealthcheckEndpoint::Configuration

  TooManyStatements:
    exclude:
      - HealthcheckEndpoint::Configuration#validate_attribute

  UtilityFunction:
    exclude:
      - HealthcheckEndpoint::Configuration#build_configuration_settings
      - HealthcheckEndpoint::Configuration#validator_argument_type
      - HealthcheckEndpoint::Configuration#validator_endpoint
      - HealthcheckEndpoint::Configuration#validator_http_status_failure
      - HealthcheckEndpoint::Configuration#validator_http_status_success
      - HealthcheckEndpoint::Configuration#validator_services_callable
      - HealthcheckEndpoint::Resolver#configuration

exclude_paths:
  - spec/support/helpers
